### PR TITLE
Migrate article: Java 8 Nashorn CLI use case: adding ISO 8601 instant to CSV with UNIX timestamp

### PR DESCRIPTION
**Pull request by Zegnat**
Towards #55.

Nothing spectacular here.

The command line plugin on PrismJS seems to have a bit of an issue with the multi-line commands. I am not sure how you want them to be displayed. Currently:

Screenshot: current inline rendering of `example-usage-1.txt`

### CODE REVIEW

**Comment by Zegnat** [comment]
After a discussion with @ScalaWilliam on IRC, suggesting price as [per Work rules](http://work.scalawilliam.com/rules/): 20 USD.

This one probably took me more time than #75, but wasn’t really any more complex. Setting the suggested price the same.

**Comment by ScalaWilliam** [comment]
build.sh conflict :/ may be easier to put changes into different places for each different PR - but ideally do them sequentially. My preference is the latter, as it makes the work items more continuous rather than staggered/batched, and it's easier to space everything out. Speed for me is not of concern yet.

**Comment by Zegnat** [comment]
> build.sh conflict :/ may be easier to put changes into different places for each different PR - but ideally do them sequentially.

The problem is git. I think it would play nice if I only appended lines to the `build.sh`, but they must be added **before** sitemap generation and adding the analytics snippet. Because of that, git is always going to complain that lines are being added at the same place in the file 😞

**Comment by Zegnat** [comment]
Rebased. I will rebase #83 after this one has been accepted and merged.

**Pull request merged**
